# yaml-language-server: $schema=https://json.schemastore.org/chart
---
apiVersion: v2
appVersion: 5.1.1
description: A meta search for newznab indexers and torznab trackers.
name: nzbhydra2
version: 0.0.4
kubeVersion: ">=1.16.0-0"
keywords:
  - nzbhydra2
  - usenet
home: https://github.com/theotherp/nzbhydra2
icon: https://github.com/theotherp/nzbhydra2/blob/master/misc/images/favicons/favicon196.png
sources:
  - https://github.com/theotherp/nzbhydra2
maintainers:
  - name: reefland
    email: reefland@gmail.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
